### ISSUE TITLE
Broken link to Compass

### ISSUE THREAD

**Issue by cphelps** [thesassway/thesassway.com#64]
The link to "the actual version of Compass" on this page is broken: 
http://www.thesassway.com/intermediate/leveraging-sass-mixins-for-cleaner-code

![image](https://cloud.githubusercontent.com/assets/7874863/4957905/fcdcf5e0-66a8-11e4-8fe4-d8c6a2f72bbe.png)

Broken page: https://github.com/Compass/compass/blob/stable/frameworks/compass/stylesheets/compass/css3/_border-radius.scss

**Comment by jlong** [comment]
@cphelps These should all be fixed now. Sorry for the long delay!

**Comment by cphelps** [comment]
Awesome. Thanks so much, John!

Sincerely, Candace
