### ISSUE TITLE
Puma is failing

### ISSUE THREAD

**Issue by blackfalcon** [thesassway/thesassway.com#65]
When running `rake server` I get the following output

```
15:34:03: (master=) thesassway.com$ rake server
15:34:37 web.1  | started with pid 20472
15:34:38 web.1  | Puma starting in single mode...
15:34:38 web.1  | * Version 2.7.1, codename: Earl of Sandwich Partition
15:34:38 web.1  | * Min threads: 0, max threads: 16
15:34:38 web.1  | * Environment: -t
15:34:38 web.1  | ERROR: No application configured, nothing to run
15:34:38 web.1  | exited with code 1
15:34:38 system | sending SIGTERM to all processes
```

All gems installed and running rbenv with `2.0.0p195`

Not sure where to go from here?

**Comment by hakunin** [comment]
I gues you're missing the puma config file or something?

**Comment by jlong** [comment]
Hey guys. I'm going to close this one for now. But if you are still interested in working on it reopen this and we can try to figure it out together.
