### ISSUE TITLE
NEWS: Call for papers now open for @CSSDevConf 2014 on Queen Mary in Long Beach

### ISSUE THREAD

**Issue by teleject** [thesassway/thesassway.com#66]
like CSS? Love Sass? Call for proposals is open now at @CSSDevConf 2015 on @TheQueenMary, CA. Submit today! - http://cssdevconf.com/

**Comment by jlong** [comment]
Thanks! Tweeted this morning.

**Comment by teleject** [comment]
Thanks, @jlong!
