### ISSUE TITLE
News: 8 Rules to Improve You CSS

### ISSUE THREAD

**Issue by czajkovsky** [thesassway/thesassway.com#67]
**Url**
https://netguru.co/blog/8-rules-improve-css

**Tweet**
There’s always something to improve in CSS, but how? @netguru dev @czajkovsky shares his 8 ideas. Check it out! https://netguru.co/blog/8-rules-improve-css

**Description**
8 rules that'll help keep your CSS clean, well-written, and in line with best practices. When combined, these rules will give you the ultimate template for good, scalable CSS architecture.

**Comment by jlong** [comment]
Tweeted.

**Comment by czajkovsky** [comment]
Thanks!
