### ISSUE TITLE
Sass Summit 2015 is Nov. 18-19

### ISSUE THREAD

**Issue by teleject** [thesassway/thesassway.com#72]
The 2-day virtual, live Sass Summit 2015 is Nov. 18-19. Attend without travel hassle - http://SassSummit.com/

**Comment by jlong** [comment]
@teleject Sorry to miss this. Would you still like for me to tweet about this?

**Comment by teleject** [comment]
This one is good, but can you wait till Monday to tweet it?

**Comment by jlong** [comment]
Sure thing. Feel free to remind me if I forget for some reason. I've added a reminder on my calendar. ;)

**Comment by jlong** [comment]
Tweeted!

**Comment by teleject** [comment]
Thank you!
