### ISSUE TITLE
Easy Grid Layout

### ISSUE THREAD

**Issue by Neeraj-pant** [thesassway/thesassway.com#74]
Grid layout with sass. 
clean and less code for flexible grids.

**Comment by jlong** [comment]
@Neeraj-pant We do have this article: http://thesassway.com/intermediate/simple-grid-mixins

Is this what you are looking for?

**Comment by Neeraj-pant** [comment]
I've created a grid mixin but actually i am totally confused in gutter space.
in mixin that i created it is pretty simple and easy but the problem is in the gutter space,
so please let me knew if there is any chance of enhancing this mixin.
here is the code........
.sass-grid{
  .grid{
    /* @include grid($desktop, $tablet, $phone)*/
    @include grid(6, 4, 3);
    /* grid style*/
  }
  &:after{
    clear: both;
    display: table;
    content: "";
  }
}


@mixin grid($desktop, $tab, $phone){
  @media (max-width: 1366px) and (min-width: 991px){
    width: 100% / $desktop - 2%;
  }
  @media (max-width: 990px) and (min-width: 769px){
    width: 100% / $tab - 2%;
  }
  @media (max-width: 768px){
    width: 100% / $phone - 2%;
  }
  padding: 1%;
  float: left;
}   


<section class="sass-grid">
    <div class="grid">
    </div>
   .......
</section>
