### ISSUE TITLE
Provide editing

### ISSUE THREAD

**Issue by xi** [thesassway/thesassway.com#75]
I have started writing an article about color contrast. I think it would be a good fit for your "advanced" section. Unfortunately I am not a good writer (yet). So what I would really like is to get help from an editor (not 100% sure if this is the right term).

- Is it possible to get help from an editor before sending in an article?
- How can I contact you about this? (the unfinished text is not published anywhere and I do not have a twitter account)

It would also be nice if  CONTRIBUTING.md would be updated to cover this case in more detail.

**Comment by jlong** [comment]
I can help. Just submit a pull requests I'll work out the edits during the merge!

--John

**Comment by xi** [comment]
Thanks for the feedback. I opened #76.
