### ISSUE TITLE
CSS not loading on some pages

### ISSUE THREAD

**Issue by ajkandy** [thesassway/thesassway.com#85]
This page: http://thesassway.com/intermediate/understanding-placeholder-selectors

Seems to be missing not just CSS, but not even rendering as plain HTML, it's loading as pure source code in the browser, when clicked on from the article list. Apparently the entire page's code is wrapped in a `pre` tag when viewed in Inspector - see screenshot.
<img width="1992" alt="Screen Shot 2019-06-03 at 5 02 50 AM" src="https://user-images.githubusercontent.com/8367286/58797299-e55e0200-85bc-11e9-98d8-5ec7fd9da91b.png">

**Comment by jlong** [comment]
Should be fixed now!
